server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate.ddl-auto: update
#    hibernate.ddl-auto: create
    show-sql: true